Repository sourceboat/laravel-clockify-api, pull requests merged in 2020-10, with the labels that each got.

#1 Feature/init project
  .editorconfig
  .gitignore
  composer.json
  config/clockify.php
  phpcs.xml
  phpmd.xml
  phpunit.xml
  src/LaravelClockifyApiServiceProvider.php
  src/Reports/ClockifyDetailedReport.php
  src/Reports/ClockifyReport.php
  src/Reports/ClockifySummaryReport.php
  src/Repositories/ClockifyRepository.php
Labels: enhancement, hacktoberfest-accepted

#7 Add travis ci
  .travis.yml
Labels: enhancement, hacktoberfest-accepted

#6 Add basic readme
  README.md
Labels: documentation, enhancement, hacktoberfest-accepted

#8 Fix imports
  src/Repositories/ClockifyRepository.php
Labels: bug, hacktoberfest-accepted

#9 Fix required php version
  composer.json
Labels: bug, hacktoberfest-accepted

#11 Add missing attributes and add link to clockify api description
  README.md
Labels: documentation, hacktoberfest-accepted

#10 add dependabot support
  .github/dependabot.yml
Labels: enhancement, hacktoberfest-accepted

#13 Feature/add possibility to specify contained in timeentry for tags
  README.md
  src/Reports/ClockifyDetailedReport.php
  src/Reports/ClockifyReport.php
  src/Reports/ClockifySummaryReport.php
Labels: enhancement, hacktoberfest-accepted

#12 Add test setup and initial test
  composer.json
  phpunit.xml
  tests/Feature/SummaryReportTest.php
  tests/TestCase.php
Labels: enhancement, hacktoberfest-accepted

#16 Capsulate some logic into separate traits
  src/Reports/ClockifyReport.php
  src/Reports/Traits/HasTags.php
  src/Reports/Traits/HasTimes.php
Labels: enhancement, hacktoberfest-accepted
